from pathlib import Path

WORKSPACE = Path(__file__).parent.parent / "spiders_workspace"
WORKSPACE.mkdir(exist_ok=True)


def build_spider_code(spider: dict, crawl_job_id: str, db_path: str) -> str:
    name = spider["name"].lower().replace(" ", "_").replace("-", "_")
    start_urls_repr = repr(spider.get("start_urls", []))
    fields = spider.get("fields", [])

    extract_lines = []
    for field in fields:
        sel_type = field.get("type", "css")
        attr = field.get("attr", "text")
        selector = field.get("selector", "")
        field_name = field.get("name", "field")
        if sel_type == "css":
            if attr == "text":
                line = f'        item["{field_name}"] = response.css("{selector}::text").get(default="").strip()'
            elif attr == "html":
                line = f'        item["{field_name}"] = response.css("{selector}").get(default="")'
            else:
                line = f'        item["{field_name}"] = response.css("{selector}::attr({attr})").get(default="")'
        else:
            if attr == "text":
                line = f'        item["{field_name}"] = response.xpath("{selector}/text()").get(default="").strip()'
            else:
                line = f'        item["{field_name}"] = response.xpath("{selector}/@{attr}").get(default="")'
        extract_lines.append(line)

    extract_code = "\n".join(extract_lines) if extract_lines else '        item["raw_text"] = response.text[:500]'

    follow_code = ""
    if spider.get("follow_links") and spider.get("follow_link_selector"):
        follow_code = f"""
        for href in response.css(\"{spider['follow_link_selector']}::attr(href)\").getall():
            yield response.follow(href, callback=self.parse)
"""

    custom_code = spider.get("custom_code", "")
    playwright_meta = 'meta={"playwright": True}' if spider.get("use_playwright") else ""

    settings_block = f"""
    custom_settings = {{
        "DOWNLOAD_DELAY": {spider.get("download_delay", 1.0)},
        "RANDOMIZE_DOWNLOAD_DELAY": {spider.get("randomize_delay", True)},
        "ROBOTSTXT_OBEY": {spider.get("respect_robots", True)},
        "CLOSESPIDER_PAGECOUNT": {spider.get("max_pages", 100)},
        "ITEM_PIPELINES": {{
            "harvester_runtime_pipeline.HarvesterPipeline": 300,
            "harvester_dedup_pipeline.HarvesterDedupPipeline": 100,
        }},
        "HARVESTER_CRAWL_JOB_ID": "{crawl_job_id}",
        "HARVESTER_DB_PATH": r"{db_path}",
        "HARVESTER_SPIDER_ID": "{spider['id']}",
    }}
"""
    if spider.get("rotate_user_agent"):
        settings_block = settings_block.rstrip("}\n") + """
        "DOWNLOADER_MIDDLEWARES": {
            "harvester_antibot_middleware.AntiBotMiddleware": 543,
        },
"""
        settings_block += "    }\n"

    code = f'''# AUTO-GENERATED BY HARVESTER - DO NOT EDIT MANUALLY
import scrapy
import sys
sys.path.insert(0, r"{str(WORKSPACE)}")


class {name.title().replace("_", "")}Spider(scrapy.Spider):
    name = "{name}"
    start_urls = {start_urls_repr}
{settings_block}
    def start_requests(self):
        for url in self.start_urls:
            yield scrapy.Request(url, callback=self.parse, {playwright_meta})

    def parse(self, response):
        item = {{}}
        item["_url"] = response.url
{extract_code}
        yield item
{follow_code}

{custom_code}
'''
    return code


def write_runtime_pipeline(workspace: Path):
    code = '''
import json
import hashlib
import sqlite3
import uuid
from datetime import datetime


class HarvesterPipeline:
    def open_spider(self, spider):
        db_path = spider.settings.get("HARVESTER_DB_PATH")
        self.crawl_job_id = spider.settings.get("HARVESTER_CRAWL_JOB_ID")
        self.spider_id = spider.settings.get("HARVESTER_SPIDER_ID")
        self.conn = sqlite3.connect(db_path)
        self.cur = self.conn.cursor()

    def process_item(self, item, spider):
        data = dict(item)
        item_id = str(uuid.uuid4())
        url = data.pop("_url", "")
        fingerprint = hashlib.md5(
            f"{self.spider_id}:{url}:{json.dumps(data, sort_keys=True)}".encode("utf-8")
        ).hexdigest()
        self.cur.execute(
            "INSERT INTO scraped_items (id, crawl_job_id, spider_id, data, url, fingerprint, scraped_at) VALUES (?, ?, ?, ?, ?, ?, ?)",
            (
                item_id,
                self.crawl_job_id,
                self.spider_id,
                json.dumps(data),
                url,
                fingerprint,
                datetime.utcnow().isoformat(),
            ),
        )
        self.conn.commit()
        self.cur.execute(
            "UPDATE crawl_jobs SET items_scraped = items_scraped + 1 WHERE id = ?",
            (self.crawl_job_id,),
        )
        self.conn.commit()
        return item

    def close_spider(self, spider):
        self.conn.close()
'''
    (workspace / "harvester_runtime_pipeline.py").write_text(code, encoding="utf-8")


def write_dedup_pipeline(workspace: Path):
    code = '''
import hashlib
import json


class HarvesterDedupPipeline:
    def __init__(self):
        self.seen = set()

    def process_item(self, item, spider):
        fp = hashlib.md5(json.dumps(dict(item), sort_keys=True).encode()).hexdigest()
        if fp in self.seen:
            from scrapy.exceptions import DropItem
            raise DropItem("Duplicate item")
        self.seen.add(fp)
        return item
'''
    (workspace / "harvester_dedup_pipeline.py").write_text(code, encoding="utf-8")


def write_antibot_middleware(workspace: Path):
    code = '''
import random

try:
    from fake_useragent import UserAgent
    _ua = UserAgent()
    def get_ua():
        return _ua.random
except Exception:
    _UA_LIST = [
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/125.0.0.0 Safari/537.36",
        "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 Safari/605.1.15",
        "Mozilla/5.0 (X11; Linux x86_64; rv:127.0) Gecko/20100101 Firefox/127.0",
    ]
    def get_ua():
        return random.choice(_UA_LIST)


class AntiBotMiddleware:
    ACCEPT_LANGUAGES = ["en-US,en;q=0.9", "en-GB,en;q=0.8", "en;q=0.7"]

    def process_request(self, request, spider):
        request.headers["User-Agent"] = get_ua()
        request.headers["Accept-Language"] = random.choice(self.ACCEPT_LANGUAGES)
        request.headers["Accept"] = "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8"
        request.headers["Accept-Encoding"] = "gzip, deflate, br"
        request.headers["Sec-Fetch-Dest"] = "document"
        request.headers["Sec-Fetch-Mode"] = "navigate"
        request.headers["Sec-Fetch-Site"] = "none"
        request.headers["Upgrade-Insecure-Requests"] = "1"
        return None
'''
    (workspace / "harvester_antibot_middleware.py").write_text(code, encoding="utf-8")


def write_spider_file(spider: dict, crawl_job_id: str, db_path: str) -> Path:
    code = build_spider_code(spider, crawl_job_id, db_path)
    filename = WORKSPACE / f"spider_{crawl_job_id}.py"
    filename.write_text(code, encoding="utf-8")
    write_runtime_pipeline(WORKSPACE)
    write_antibot_middleware(WORKSPACE)
    write_dedup_pipeline(WORKSPACE)
    return filename
